export const PlayersData =[
    {id: 1, name: 'Cristiano Ronaldo', cost: 20000000, club: 'Manchester United', img:'assets/images/cr.jpg', clip:'https://www.youtube.com/embed/mhfJSTJTnXU',
      info: 'Cristiano Ronaldo dos Santos Aveiro was born 5 February 1985 is a Portuguese professional footballer who plays as a forward for Premier League club Manchester United and captains the Portugal national team.'},
    {id: 2, name: 'N Golo Kanté', cost: 40000000, club: 'Chelsea', img:'assets/images/kante.jpg', clip:'https://www.youtube.com/embed/9_O6TSyYAlE',
      info: 'N Golo Kanté (born 29 March 1991) is a French professional footballer who plays as a central midfielder for Premier League club Chelsea and the France national team. Kanté is widely praised for his work rate and defensive acumen.'},
    {id: 3, name: 'Messi', cost: 50000000, club: 'PSG', img:'assets/images/messi.jpg', clip:'https://www.youtube.com/embed/nA8wHQvHPJU',
      info: 'Lionel Andrés Messi born 24 June 1987, also known as Leo Messi, is an Argentine professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and captains the Argentina national team. Widely regarded as one of the greatest players of all time, Messi has won a record seven Ballon d Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d Or Dream Team. Until leaving the club in 2021.'},
    {id: 4, name: 'Neymar', cost: 220000000, club: 'PSG',img:'assets/images/neymar.jpg', clip:'https://www.youtube.com/embed/OWOjRdmpM6I',
      info: 'Neymar da Silva Santos Júnior (born 5 February 1992), known as Neymar, is a Brazilian professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the Brazil national team. He is considered a versatile player, being able to play as either a central striker, second striker, winger or occasionally as an attacking midfielder. A prolific goalscorer and renowned playmaker, he is regarded as one of the best players in the world. Neymar has scored at least 100 goals for three different clubs, making him one of three players to achieve this'},
    {id: 5, name: 'Harry Kane', cost: 90000000, club: 'Tottenham',img:'assets/images/kane.jpg', clip:'https://www.youtube.com/embed/9_O6TSyYAlE',
      info: 'Harry Edward Kane MBE (born 28 July 1993) is an English professional footballer who plays as a striker for Premier League club Tottenham Hotspur and captains the England national team. Regarded as one of the best strikers in the world, Kane is known for his prolific goalscoring record and ability to link play. He ranks as Tottenham second-highest all-time top goalscorer and the third-highest Premier League all-time top goalscorer'},
    {id: 6, name: 'Haaland', cost: 150000000, club: 'Manchester City', img:'assets/images/haaland.jpg', clip:'https://www.youtube.com/embed/EppU7FwAyEc',
      info: 'Erling Braut Haaland (né Håland; born 21 July 2000) is a Norwegian professional footballer who plays as a striker for Premier League club Manchester City and the Norway national team. Considered one of the best players in the world, he is known for his athleticism, speed and finishing.'}
  ];
